// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywaxdospunnjdzkmtjsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3YXhkb3NwdW5uamR6a210anNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTIyMDUsImV4cCI6MjA2NzkyODIwNX0.9FqdiUehWJGPU_PA0cz3UesX8H35ThggUlfnfajgA24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});